### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by phiresky** [Aleph-Alpha/ts-rs#83]
```
thread 'api_types::export_bindings_apitypests' panicked at 'internal error: entered unreachable code', .cargo/registry/src/github.com-1ecc6299db9ec823/ts-rs-6.1.2/src/lib.rs:367:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9ad5d82f822b3cb67637f11be2e65c5662b66ec0/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/9ad5d82f822b3cb67637f11be2e65c5662b66ec0/library/core/src/panicking.rs:110:14
   2: core::panicking::panic
             at /rustc/9ad5d82f822b3cb67637f11be2e65c5662b66ec0/library/core/src/panicking.rs:48:5
   3: <core::option::Option<T> as ts_rs::TS>::name
             at .cargo/registry/src/github.com-1ecc6299db9ec823/ts-rs-6.1.2/src/lib.rs:367:9
   4: <timetrackrs::api_types::ApiTypesTS as ts_rs::TS>::inline
             at ./src/api_types.rs:49:18
   5: <timetrackrs::api_types::ApiTypesTS as ts_rs::TS>::decl
             at ./src/api_types.rs:49:18
   6: ts_rs::export::generate_decl
             at .cargo/registry/src/github.com-1ecc6299db9ec823/ts-rs-6.1.2/src/export.rs:63:19
   7: ts_rs::export::export_type
             at .cargo/registry/src/github.com-1ecc6299db9ec823/ts-rs-6.1.2/src/export.rs:34:5
   8: ts_rs::TS::export
             at .cargo/registry/src/github.com-1ecc6299db9ec823/ts-rs-6.1.2/src/lib.rs:262:9
   9: timetrackrs::api_types::export_bindings_apitypests
             at ./src/api_types.rs:49:18
  10: timetrackrs::api_types::export_bindings_apitypests::{{closure}}
             at ./src/api_types.rs:49:18
  11: core::ops::function::FnOnce::call_once
```

here: https://github.com/Aleph-Alpha/ts-rs/blob/703cd15cde8ea9a27d555c5eb49f0bdb02ff6004/ts-rs/src/lib.rs#L367

when serializing this type:

```rust
    #[ts(export)]
    #[serde(tag = "type")]
    pub enum ApiTypesTS {
        time_range {
            request: TimeRangeRequest,
            response: Vec<SingleExtractedChunk>,
        },
        single_event {
            request: SingleEventRequest,
            response: Option<SingleExtractedEventWithRaw>,
        },
        rule_groups {
            request: (),
            response: Vec<TagRuleGroup>,
        },
        invalidate_extractions {
            request: InvalidateRangeRequest,
            response: (),
        },
        update_rule_groups {
            request: Vec<TagRuleGroup>,
            response: (),
        },
        get_known_tags {
            request: (),
            response: Vec<String>,
        },
        timestamp_search {
            request: TimestampSearchRequest,
            response: Option<Timestamptz>,
        },
    }
```

The macro-expanded code there has stuff like this:

```
let res = ::alloc::fmt::format(::core::fmt::Arguments::new_v1(
    &["", "", ": ", ","],
    &match (
        &"response",
        &"",
        &<Option<SingleExtractedEventWithRaw> as ts_rs::TS>::name(),
    ) {
        _args => [
            ::core::fmt::ArgumentV1::new(_args.0, ::core::fmt::Display::fmt),
            ::core::fmt::ArgumentV1::new(_args.1, ::core::fmt::Display::fmt),
            ::core::fmt::ArgumentV1::new(_args.2, ::core::fmt::Display::fmt),
        ],
    },
));
```

which calls name() on Option which I'd guess is where it throws.

**Comment by NyxCode** [comment]
I am failing to reproduce this. Could you provide a minimal reproducible example?

**Comment by phiresky** [comment]
I'm trying to convert [this code](https://github.com/phiresky/timetrackrs/blob/master/src/api_types.rs) from using [typescript_definitions](https://github.com/arabidopsis/typescript-definitions) to ts-rs. Let me know if you see something obvious in there, otherwise I'll try to create a reproducable minimal example.

**Comment by NyxCode** [comment]
```rust
    #[derive(Serialize, TS)]
    #[ts(export)]
    #[serde(tag = "type")]
    pub enum ApiTypesTS {
        time_range {
            request: i32,
            response: Vec<i32>,
        },
        single_event {
            request: i32,
            response: Option<i32>,
        },
        rule_groups {
            request: (),
            response: Vec<i32>,
        },
        invalidate_extractions {
            request: i32,
            response: (),
        },
        update_rule_groups {
            request: Vec<i32>,
            response: (),
        },
        get_known_tags {
            request: (),
            response: Vec<i32>,
        },
        timestamp_search {
            request: i32,
            response: Option<i32>,
        },
    }
```
generates
```ts
type ApiTypesTS = { type: \"time_range\", request: number, response: Array<number>, } | { type: \"single_event\", request: number, response: number | null, } | { type: \"rule_groups\", request: null, response: Array<number>, } | { type: \"invalidate_extractions\", request: number, response: null, } | { type: \"update_rule_groups\", request: Array<number>, response: null, } | { type: \"get_known_tags\", request: null, response: Array<number>, } | { type: \"timestamp_search\", request: number, response: number | null, };
```

**Comment by phiresky** [comment]
Here's a minimal example:

```rust
macro_rules! make {
    (pub enum $name:ident {
        $($r:ident { response: $resp:ty }),+
    }) => (
        #[derive(TS)]
        #[ts(export)]
        pub enum $name {
            $( $r { response: $resp }),*
        }
    )
}

make! {
    pub enum Foobar {
        single_event {
            response: Option<i32>
        }
    }
}
```

It seems to only happen when the enum is defined with a macro - even though that macro is not really doing anything?

**Comment by tsar-boomba** [comment]
I ran into this issue today, and after some testing, I can say that this is not a bug in ts-rs. I tested a struct with named fields and encountered the same error. Here is my testing code:

```rs
macro_rules! unit {
    (
        $(#[$meta:meta])*
		$struct_vis:vis struct $struct_name:ident {
			$(
				$(#[$field_meta:meta])*
				$field_vis:vis $field_name:ident : $field_type:ty
			),*$(,)+
		}
    ) => {
        $(#[$meta])*
        $struct_vis struct $struct_name {
            $(
				$(#[$field_meta])*
				$field_vis $field_name: $field_type,
			)*
        }
    };
}

unit! {
    #[derive(Debug, ts_rs::TS)]
    #[ts(export)]
    struct Test {
        pub field: Vec<String>,
        pub fieldTwo: Option<String>,
    }
}
```

After looking into ts-rs' source, I found the culprit to be the `extract_type_args` function in `types/generics.rs` in the macros crate. Essentially the problem is that when the declarative macro gets expanded, the types get parsed as `Type::Group` instead of `Type::Path`. This leads the `extract_type_args` to try and find generics on `String` and fail and falls back to the `TS` blanket impl on `Option<T> where T: TS` which has `name` as unreachable. This is either a bug in the `syn` crate or with how rustc expands declarative macros. For now this can be worked around by using fully qualified paths for types with generics in macro declarations. For example, the code above will work as:

```rs
macro_rules! unit {
    (
        $(#[$meta:meta])*
		$struct_vis:vis struct $struct_name:ident {
			$(
				$(#[$field_meta:meta])*
				$field_vis:vis $field_name:ident : $field_type:ty
			),*$(,)+
		}
    ) => {
        $(#[$meta])*
        $struct_vis struct $struct_name {
            $(
				$(#[$field_meta])*
				$field_vis $field_name: $field_type,
			)*
        }
    };
}

unit! {
    #[derive(Debug, ts_rs::TS)]
    #[ts(export)]
    struct Test {
        pub field: std::vec::Vec<String>,
        pub fieldTwo: std::option::Option<String>,
    }
}
```

I don't see any reasonable way for this to be worked around in ts-rs, so for now this will have to do. Hope this helps someone who runs into this is the future 😁 .

**Comment by escritorio-gustavo** [comment]
Closing this since @tsar-boomba presented a fix, there is no way for us to fix this since it's a `syn` bug and this issue has been inactive for two years
